### ISSUE TITLE
Space button unresponsive near top of the screen for some blocks.

### ISSUE THREAD

**Issue by RychuP** [kprega/ConsoleTetris#1]
First of all, it's a nice implementation of Tetris. I like it.

The issue I noticed is with the rotation of blocks when they first appear near top of the screen. Some blocks have pivot points in their corners rather than centers and they need to travel 2 rows down before a player can start turning them with a space button. It's especially noticeable with S and Z blocks. Feels somewhat unresponsive.

Also, pause button would be useful.

**Comment by kprega** [comment]
Thank you for your comment.
You're right, there is an issue regarding rotation. I'll see what can be done about that.
Pause button is a good idea, I'll add it too.

**Comment by kprega** [comment]
Issue fixed with commit [4250dbe](https://github.com/kprega/ConsoleTetris/commit/4250dbe5a3ee231552d26a0d37b21495b4e310de).
